---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
data <- read.csv("C:/Users/calvi/Downloads/archive (8)/understat_per_game.csv")

```

```{r}
data$h_a <- as.factor(data$h_a)
mod <- lm(scored~h_a, data)
summary(mod)
library(margins)
library(cowplot) #You won't normally need this
library(gridGraphics)#You won't normally need this
theme_set(theme_light())
#install.packages("effects")
library(effects)
marginal_effects <- effect("h_a", mod)
plot(marginal_effects, xlab = "Home vs. Away", ylab = "Scored", main = "Home vs. Away Effects")

```


```{r}
# Create a bar chart to compare two categories

data %>%
  group_by(league,h_a) %>%
  summarise(scored = mean(scored)) %>%
  ggplot(aes(x = league, y = scored, fill = h_a)) +
    geom_bar(stat = "identity", position = "dodge") +
    labs(x = "League", y = "Goals Scored", title = "Comparison of Goals between Leagues, H vs. A", fill = "Home vs. Away") +
    theme_minimal() +
    scale_fill_manual(values = c("h" = "midnightblue", "a" = "goldenrod"))

```

```{r}
data
# Create a scatter plot to compare two numerical columns
ggplot(data, aes(x = scored, y = xG, color = h_a)) +
  geom_point() +
  geom_smooth() +
  labs(x = "Goals Scored", y = "Expected Goals Scored", title = "Comparison of Goals Scored vs. Expected Goals Scored", color = "Home/Away") +
  theme_minimal() +
  scale_color_manual(values = c("h" = "midnightblue", "a" = "goldenrod"))
```

```{r}
data$total_goals <- data$scored + data$missed

ggplot(data, aes(x = total_goals)) +
  geom_histogram(aes(y = ..density..), bins = 10, fill = "midnightblue", color = "black", alpha = 0.6) +
  labs(x = "Total Goals", y = "Density", title = "Histogram with Density of Total Goals Scored") +
  theme_minimal()
```


















